service:
  name: pythonfruitsalad

plugins:
  - serverless-google-cloudfunctions

provider:
  name: google
  region: europe-west1 # OPTIONAL: Edit if you want

  # THESE TWO MUST BE UPDATED BY YOU!
  project: "yourproject" # EDIT THIS to your value
  credentials: ~/.gcloud/{KEYFILE}.json # EDIT THIS to your value

  runtime: python37
  memorySize: 256
  timeout: 5s

functions:
  fruitSalad:
    handler: fruit_salad
    events:
      - http: fruitSalad
        method: POST
